### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by ivancucer** [turbobabr/duplicator#26]
Hello @turbobabr @amonshiz

I know I know we all already switched to Figma 😇 But many of us still have some long-term projects that we have to support. And unfortunately, those projects were made using Sketch 😞

So any ideas why the plugin doesn't work under apple silicon? It only works under Rosetta 2...

Best!
Ivan

**Comment by turbobabr** [comment]
Hey Ivan, I don't use Sketch any longer and my license has expired already, thus I can't check whether it works under the latest version of Sketch even on Intel silicone. I don't use any native code or anything in the implementation - only Sketch's APIs and I tend to think that the real issue is in some changed APIs after v64.

**Comment by ivancucer** [comment]
Hey @turbobabr

Thanks for the reply. Yeah nobody uses Sketch these days and I have no idea how Sketch B.V. is still alive.

Probably there is an issue with their API which doesn't work under Apple Silicon but works perfectly under Rosetta 2.

Well, Sketch is sadly dead to me - simply because the entire community has already switched. No community = No Sketch.

Thanks anyway for all your contribution during those past years.

Best!
Ivan
